# Generated by Django 2.2.10 on 2020-10-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.CharField(max_length=100)),
                ('salary', models.PositiveIntegerField()),
                ('prefectures', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
